FROM node:lts

# install required libs, docker-compose and yarn
RUN apt-get update && apt-get install python-pip -y && pip install docker-compose

# create folder and set it as workdir
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# copy binary
COPY dist/index.js /usr/src/app/server.js

# expose ports
EXPOSE 8080

CMD ["node", "server.js"]
